#version: '3.8'
#services:
#  client:
#    build: ./client
#    container_name: client_frontend
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./client:/app
#      - ./app/node_modules
#    stdin_open: true
#    tty: true
#
version: '3.7'

services:

 frontend:
   container_name: frontend
   build: ./
   volumes:
     - './:/app'
     - '/app/node_modules'
   ports:
     - 3000:3000
   stdin_open: true
   environment:
     - CHOKIDAR_USEPOLLING=true
   command: npm start